# Generated by Django 2.2.3 on 2019-07-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_voc_app', '0003_auto_20190714_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='ability',
            field=models.IntegerField(default=-1),
        ),
    ]
