# Generated by Django 2.2.3 on 2019-07-17 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AI_voc_app', '0004_auto_20190717_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
