# Generated by Django 2.2.3 on 2019-07-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_voc_app', '0005_auto_20190717_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='ability',
            field=models.IntegerField(default=0),
        ),
    ]
