# Generated by Django 2.2.3 on 2019-07-24 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AI_voc_app', '0005_auto_20190717_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='ability',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(default='', max_length=30)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_voc_app.Vocabulary')),
            ],
        ),
    ]
